project:
  type: website

website:
  title: "Chelsea's Got the Blues"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: predict-chelsea.qmd
        text: Model's Prediction
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About Me

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

