project:
  type: website

website:
  title: "Chelsea's Got the Blues"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - predict-chelsea.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

